cart/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<book_id>\d+)/$',
        views.cart_add,
        name='cart_add'),
    url(r'^remove/(?P<book_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]

myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from shop.views import home, search, profile_edit, profile_view
from django.contrib.sitemaps.views import sitemap
from shop.sitemaps import BookSitemap

admin.site.site_header = 'DLearn admin'
admin.site.site_title = 'DLearn admin'
# admin.site.site_url = 'http://dLearn.tk/'
admin.site.index_title = 'DLearn Administration'

sitemaps = {
    'books': BookSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include("shop.urls", namespace="shop")),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^ratings/', include('star_ratings.urls',
                              namespace='ratings', app_name='ratings')),
    url(r'^daguerre/', include('daguerre.urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^account/profile/$', profile_view, name="profile_view"),
    url(r'^account/profile/edit/$', profile_edit, name="profile_edit"),
    url(r'^search/$', search, name="search"),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt', include('robots.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^$', home, name="home"),
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^list/orders/$', views.order_list, name='order_list'),
    url(r'^(?P<order_id>\d+)/download/$', views.confirm_payment, name='download'),
    url(r'^(?P<order_id>\d+)/(?P<tx_ref>[\d\w]+)/$', views.order_detail, name='order_detail'),
    url(r'^form/$', views.guest_checkout, name='order_form'),
]

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):


    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int, widget=forms.HiddenInput)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Book
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, book_id):

    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
    
        cart.add(book=book)
    return redirect('cart:cart_detail')

def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    profile_upto_date = None
    if request.user.is_authenticated:
        user = request.user
        profile_upto_date = all([user.email, user.first_name,
                             user.last_name, user.username])
    return render(request, 'cart/detail.html', {'cart': cart, 'profile_update': profile_upto_date})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load humanize %}
{% block title %}
    Checkout
{% endblock title %}
    
{% block content %}
<!-- breadcrumbs -->
{% include 'shop/partials/breadcrumbs.html' %}
<!-- //breadcrumbs -->
<!-- checkout -->
	<div class="checkout">
		<div class="container">
			
			 {% if request.user.is_authenticated %} {% if not profile_update %}
			<div class="alert alert-danger text-center">
				Your profile needs to be updated. Click
				<a href="{% url 'profile_edit' %}">here</a> to update it.
			</div>
			
			{% endif %} {% endif %}
			<h3 class="animated wow slideInLeft" data-wow-delay=".5s">Your shopping cart contains: <span>{{ cart|length }} Books</span></h3>
			<div class="checkout-right animated wow slideInUp" data-wow-delay=".5s">
				<table class="timetable_sub">
					<thead>
						<tr>
							<th>SL No.</th>	
							<th>Product</th>
							<th>Product Name</th>
							<th>Price</th>
							<th>Remove</th>
						</tr>
                    </thead>
                    
                    {% for item in cart %}
                      
                    {% with product=item.book %}
					<tr class="rem{{ forloop.counter }}">
                        
						<td class="invert">{{ forloop.counter }}</td>
						<td class="invert-image"><a href="{{ product.get_absolute_url }}">
							<img src="{% if product.image %}{{ product.image.url }}{% else %}{{ product.image_url }}{% endif %}" alt=" " class="img-responsive" /></a></td>
						
						<td class="invert">{{ product.title }}</td>
						<td class="invert">{% if product.featured %}₦{{ product.discount_price|intcomma }} {% else %}₦{{ product.price|intcomma }}{% endif %}</td>
						<td class="invert">
							<div class="rem">
								<a class="close close{{ forloop.counter }}" href="{% url 'cart:cart_remove' product.id %}"> </a>
							</div>
							<script>$(document).ready(function(c) {
								$('.close{{ forloop.counter }}').on('click', function(c){
									$('.rem{{ forloop.counter }}').fadeOut('slow', function(c){
										$('.rem{{ forloop.counter }}').remove();
									});
									});	  
								});
						   </script>
						</td>
                    </tr>
                    {% endwith %}
                    {% endfor %}
					
				</table>
			</div>
			<div class="checkout-left">	
				<div class="checkout-left-basket animated wow slideInLeft" data-wow-delay=".5s">
					<h4>Continue to basket</h4>
					<ul>
                        {% for item in cart %}
                          
                        <li>{{ item.book.title|truncatewords:3 }} <i>-</i> <span>₦{% if item.book.featured %}{{ item.book.discount_price|intcomma }} {% else %}{{ item.book.price|intcomma }}{% endif %} </span></li>
                        {% endfor %}
						
						<li><b>Total</b> <i>-</i> <span>₦{{ cart.get_total_price|intcomma }}</span></li>
					</ul>
					
				</div>
				<div class="checkout-right-basket animated wow slideInRight" data-wow-delay=".5s">
					
					<a href="#" onclick="window.history.back()"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>Continue Shopping</a>
					<a href="{% url "orders:order_create" %}">Checkout (pay) &nbsp;&nbsp;<span class="glyphicon glyphicon-menu-right" aria-hidden="true"> </span></a>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //checkout -->
{% endblock content %}