cart/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<book_id>\d+)/$',
        views.cart_add,
        name='cart_add'),
    url(r'^remove/(?P<book_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]

myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from shop.views import home, search, profile_edit, profile_view
from django.contrib.sitemaps.views import sitemap
from shop.sitemaps import BookSitemap

admin.site.site_header = 'DLearn admin'
admin.site.site_title = 'DLearn admin'
# admin.site.site_url = 'http://dLearn.tk/'
admin.site.index_title = 'DLearn Administration'

sitemaps = {
    'books': BookSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include("shop.urls", namespace="shop")),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^ratings/', include('star_ratings.urls',
                              namespace='ratings', app_name='ratings')),
    url(r'^daguerre/', include('daguerre.urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^account/profile/$', profile_view, name="profile_view"),
    url(r'^account/profile/edit/$', profile_edit, name="profile_edit"),
    url(r'^search/$', search, name="search"),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt', include('robots.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^$', home, name="home"),
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^list/orders/$', views.order_list, name='order_list'),
    url(r'^(?P<order_id>\d+)/download/$', views.confirm_payment, name='download'),
    url(r'^(?P<order_id>\d+)/(?P<tx_ref>[\d\w]+)/$', views.order_detail, name='order_detail'),
    url(r'^form/$', views.guest_checkout, name='order_form'),
]

shop/urls.py
from django.conf.urls import url

from .views import product_list, product_detail, home

urlpatterns = [
    url(r'^$', product_list, name="book_list"),
    url(r'^(?P<category_slug>[-\w]+)/$', product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', product_detail, name="book_detail"),
]

shop/models.py
import datetime

from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from taggit.managers import TaggableManager

from .validators import (validate_isbn, validate_price,
                         validate_year_is_not_future)

ALLOWED_EXTENSIONS = ['pdf']


class Category(models.Model):

    name = models.CharField(max_length=200, db_index=True)
    description = models.TextField(max_length=200, default="")
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)

    class Meta:
        ordering = 'name',
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", kwargs={"category_slug": self.slug})


class Book(models.Model):
    category = models.ForeignKey(
        Category, related_name='books', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    author = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='books/%Y/%m/%d', blank=True)
    image_url = models.URLField(max_length=400, blank=True,
                                help_text=("this should be provided only if "
                                    "you don't want to upload an image and"
                                    " would rather use an image from "
                                    "google or any other medium. "
                                    "This must be a URL"))
    featured = models.BooleanField(default=False)
    book_file = models.FileField(
        upload_to='books/file/%Y/%m/%d', max_length=100,
        validators=[FileExtensionValidator(ALLOWED_EXTENSIONS,
                                           "Only pdf files are allowed")], blank=True)
    book_url = models.URLField(max_length=400, blank=True,
                               help_text=("this should be provided only if "
                                    "you don't want to upload a book file and"
                                    " would rather use a book from "
                                    "google or any other medium. "
                                    "This must be a URL"))
    description = models.TextField(blank=True)
    price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0, validators=[validate_price])
    discount_price = models.DecimalField(max_digits=10, decimal_places=2,
                                         default=0,
                                         validators=[MinValueValidator(0, "Discount Price must be positive")
                                         ])
    year = models.DateField(default=timezone.now, validators=[
                            validate_year_is_not_future])
    num_pages = models.IntegerField("Number of pages", default=100)
    publisher = models.CharField(max_length=100)
    isbn = models.CharField(
        max_length=13, blank=True, null=True, validators=[validate_isbn])

    file_format = models.CharField(max_length=10, default="PDF")
    tags = TaggableManager()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = '-created',
        index_together = (('id', 'slug'),)

    def clean(self):
        if self.isbn:
            if len(self.isbn) < 10 or len(self.isbn) in (11, 12):
                raise ValidationError('ISBN must be 10 or 13 characters long')
        if self.price:
            if self.price < 0:
                raise ValidationError("Price can't be negative")

        if self.year.year > datetime.date.today().year:
            raise ValidationError("Year cannot be in the future")

        if not self.image and not self.image_url:
            raise ValidationError({'image_url': "Since you didn't upload any image for "
                                                "this book, you must enter a URL"
                                                " to an Image file"})
        if not self.book_file and not self.book_url:
            raise ValidationError({'book_url': "Since you didn't upload any book file for "
                                               "this book, you must enter a URL"
                                               " to book file"})

    def __str__(self):
        return self.title

    @property
    def name(self):
        return self.title

    def save(self, *args, **kwargs):
        self.clean()
        if not self.slug:
            self.slug = slugify(self.title)
        if self.featured:
            qs = Book.objects.filter(featured=True).exclude(pk=self.pk)
            if qs.exists():
                qs.update(featured=False)
                
        super(Book, self).save(*args, **kwargs)  # Call the real save() method

    def get_absolute_url(self):

        return reverse('shop:book_detail', kwargs={'id': self.pk, 'slug': self.slug})

shop/forms.py
from django import forms
from django.contrib.auth.models import User

class SearchForm(forms.Form):
    q = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': "Search using book titles, publisher and authors"}))

class UserEditForm(forms.ModelForm):
    """Form definition for UserEdit."""

    class Meta:
        """Meta definition for UserEditform."""

        model = User
        fields = ('first_name', 'last_name', 'username')

    

shop/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User
from cart.forms import CartAddProductForm
from elasticsearch_dsl import Search
from pages.models import DiscountSection
from shop.forms import SearchForm, UserEditForm
from newsletter.models import Newsletter
from .models import Book, Category


def home(request):
    featured = Book.objects.filter(featured=True).first()
    discount = DiscountSection.objects.filter(active=True).first()
    cart_product_form = CartAddProductForm(initial={'quantity': "1",
                                                    'update': False})
    total_books = Book.objects.count()
    # newsletter = Newsletter.objects.first()
    newsletter = "new-books"
    return render(request, "shop/home.html",
                  {'featured': featured,
                   'cart_product_form': cart_product_form,
                   'discount': discount,
                   'newsletter': newsletter,
                   'total_books': total_books})


def product_list(request, category_slug=None):

    category = None
    categories = Category.objects.all()
    object_list = Book.objects.only('image', 'price', 'book_file').all()
    discount = DiscountSection.objects.filter(active=True).first()

    cart_product_form = CartAddProductForm(initial={'quantity': "1",
                                                    'update': False})
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category=category).only(
            'image', 'price', 'book_file')

    paginator = Paginator(object_list, 9)
    page = request.GET.get('page')
    try:

        books = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        books = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        books = paginator.page(paginator.num_pages)

    return render(request,
                  'shop/product_list.html',
                  {'category': category,
                   'page_obj': page,
                   'categories': categories,
                   'books': books,
                   'cart_product_form': cart_product_form,
                   'discount': discount})


def product_detail(request, id, slug):
    book = get_object_or_404(Book, id=id, slug=slug)
    categories = Category.objects.only('slug', 'name').all()
    discount = DiscountSection.objects.filter(active=True).first()
    cart_product_form = CartAddProductForm(initial={'quantity': "1",
                                                    'update': False})
    book_tags_ids = book.tags.values_list('id', flat=True)
    similar_books = Book.objects.filter(tags__in=book_tags_ids)\
        .exclude(id=book.id).only('image', 'price', 'book_file')
    similar_books = similar_books.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-year')[:4]
    return render(request,
                  'shop/product_detail.html',
                  {'book': book, 'categories': categories,
                   'similar_books': similar_books,
                   'cart_product_form': cart_product_form,
                   'discount': discount})


def search(request):
    cart_product_form = CartAddProductForm(initial={'quantity': "1",
                                                    'update': False})
    if request.method == "GET":
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["q"]
            search = Search(index=["books"]).query(
                "multi_match",
                query=query,
                fields=['title', 'author', 'publisher'])
            total = search.count()
            search = search[0:total]
            results = search.execute()
            results = results.hits

            paginator = Paginator(results, 12)
            page = request.GET.get('page')
            try:
                results = paginator.page(page)
            except PageNotAnInteger:
                # If page is not an integer deliver the first page
                results = paginator.page(1)
            except EmptyPage:
                # If page is out of range deliver last page of results
                results = paginator.page(paginator.num_pages)
            return render(request, "shop/search.html", {'results': results,
                                                        'total_results': total,
                                                        'query': query,
                                                        "cart_product_form": cart_product_form})


@login_required
def profile_edit(request):
    if request.method == "POST":
        form = UserEditForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        form = UserEditForm(instance=request.user)
    return render(request, 'account/profile_edit.html', {'form': form})


@login_required
def profile_view(request):
    user = get_object_or_404(User, email=request.user.email)

    profile_upto_date = all([user.email, user.first_name,
                             user.last_name, user.username])
    return render(request, "account/profile_view.html",
                  {'user': user,
                   "profile_upto_date": profile_upto_date})

shop/templates/shop/partials/add_to_cart_btn.html
{% if book %}
  {% if book.price == 0.00 %}

<a 
  class="item_add" 
  download="{% if book.book_file %}{{ book.book_file.url }}{% else %}{{ book.book_url }}{% endif %}" 
  href="{% if book.book_file %}{{ book.book_file.url }}{% else %}{{ book.book_url }}{% endif %}">
    download
</a>
{% else %}

<form action="{% url 'cart:cart_add' book.id %}" method="post">
    {% csrf_token %} {{ cart_product_form }}
    <input class="btn" type="submit" value="ADD TO CART">
</form>

{% endif %}
{% endif %}

shop/templates/shop/partials/breadcrumbs.html
<div class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
            <li>
                <a href="{% url 'home' %}">
                    <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a>
            </li>
            <li class="active">Products</li>
        </ol>
    </div>
</div>

shop/templates/shop/partials/categories.html
<div class="categories animated wow slideInUp" data-wow-delay=".5s">
    <h3>Categories</h3>
    <ul class="cate">
        <li {% if not category.slug %}class="active"{% endif %}>
            <a href="{% url 'shop:book_list' %}">All</a>
        </li>
        {% for c in categories %}
          <li {% if category.slug == c.slug %}class="active"{% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
        
        
    </ul>
</div>

shop/templates/shop/partials/footer.html
<!-- footer -->
<div class="footer">
    <div class="container">
        
        <div class="footer-logo animated wow slideInUp" data-wow-delay=".5s">
            <h4 class="h2"><a href="{% url 'home' %}">DLearn <span>Digital Learning</span></a></h4>
        </div>
        <div class="copy-right animated wow slideInUp" data-wow-delay=".5s">
            <p>&copy 2016-2018 DLearn. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
        </div>
    </div>
</div>
<!-- //footer -->

shop/templates/shop/partials/header.html
{% load static %}
{% load humanize %}
<!-- header -->
<div class="header">
    <div class="container">
        <div class="header-grid">
            <div class="header-grid-left animated wow slideInLeft" data-wow-delay=".5s">
                <ul>
                    <li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:snpet.hub@gmail.com.com">@dlearn.tk</a></li>
                   
                   {% if not request.user.is_authenticated %}
                    <li><i class="glyphicon glyphicon-log-in" aria-hidden="true"></i><a href="{% url 'account_login' %}">Login</a></li>
                    <li><i class="glyphicon glyphicon-book" aria-hidden="true"></i><a href="{% url 'account_signup' %}">Register</a></li>
                    {% else %}
                    <li><i class="glyphicon glyphicon-log-out" aria-hidden="true"></i><a href="{% url 'account_logout' %}">Sign Out</a></li>
                   {% endif %}
                       
                </ul>
            </div>
            <div class="header-grid-right animated wow slideInRight" data-wow-delay=".5s">
                <ul class="social-icons">
                        
                    <li><a href="https://web.facebook.com/DLearn.tk/?ref=br_rs" class="facebook"></a></li>
                    <li><a href="#" class="twitter"></a></li>
                    <li><a href="#" class="g"></a></li>
                    <li><a href="#" class="instagram"></a></li>
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="logo-nav">
            <div class="logo-nav-left animated wow zoomIn" data-wow-delay=".5s">
                <h1><a href="{% url 'home' %}">DLearn <span>Digital Learning</span></a></h1>
            </div>
            <div class="logo-nav-left1">
                <nav class="navbar navbar-default">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header nav_2">
                    <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div> 
                <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
                    <ul class="nav navbar-nav">
                        
                        <li {% if menu == 'home' %}class="active"{% endif %}><a href="{% url 'home' %}" {% if menu == 'home' %}class="act"{% endif %}>Home</a></li>
                        
                        <li {% if menu == "shop" %}class="active"{% endif %}><a href="{% url 'shop:book_list' %}" {% if menu == 'shop' %}class="act"{% endif %}>All Books</a></li>
                        <!-- <li><a href="mail.html">Mail Us</a></li> -->
                        {% if request.user.is_authenticated %}
                          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                            <ul class="dropdown-menu multi-column">
                                <div class="row">
                                    <div class="col-sm-offset-1 col-sm-11">
                                        <ul class="multi-column-dropdown">
                                            
                                            <li><a href="{% url 'profile_view' %}">Profile</a></li>
                                            <li><a href="{% url 'orders:order_list' %}">Orders</a></li>
                                            <hr>
                                            <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
                                            
                                        </ul>
                                    </div>
                                    
                                    
                                    <div class="clearfix"></div>
                                </div>
                            </ul>
                        </li>
                        
                        {% endif %}
                        
                            
                    </ul>
                </div>
                </nav>
            </div>
            <div class="logo-nav-right">
                <div class="search-box">
                    <div id="sb-search" class="sb-search">
                        <form action="{% url 'search' %}">
                            <input class="sb-search-input" placeholder="Search using book titles, publisher and authors" type="search" id="search" name="q">
                            <input class="sb-search-submit" type="submit" value="">
                            <span class="sb-icon-search"> </span>
                        </form>
                    </div>
                </div>
                    <!-- search-scripts -->
                    <script src="{% static 'shop/js/classie.js' %}"></script>
                    <script src="{% static 'shop/js/uisearch.js' %}"></script>
                        <script>
                            new UISearch( document.getElementById( 'sb-search' ) );
                        </script>
                    <!-- //search-scripts -->
            </div>
            <div class="header-right">
                <div class="cart box_1">
                    <a href="{% url 'cart:cart_detail' %}">
                        <h3> <div class="total">
                            <span class="">₦{{ cart.get_total_price|intcomma }}</span> (<span id="" class=""></span>{{ cart|length }} book{{ cart|length|pluralize }})</div>
                            <img src="{% static 'shop/images/bag.png' %}" alt="Cart" />
                        </h3>
                    </a>
                    <p><a href="javascript:;" class="simpleCart_empty">Empty Cart</a></p>
                    <div class="clearfix"> </div>
                </div>	
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //header -->

shop/templates/shop/partials/list_item.html
{% load humanize %}
{% load static %}
{% load ratings %}
{% load daguerre %}
<div class="new-collections-grid1 products-right-grid1 animated wow slideInUp" data-wow-delay=".5s">
        <div class="new-collections-grid1-image">
            <a href="{{ book.get_absolute_url }}" class="product-image">
                {% if book.image %}
                <img src="{% adjust book.image 'fill' width=180 height=236 %}"
                   class="img-responsive" alt="{{ book.title }}">
                {% else %}
                <img src="{{ book.image_url }}" height="236" width="180" class="img-responsive" alt="{{ book.title }}">
                {% endif %}
            </a>
            <div class="new-collections-grid1-image-pos products-right-grids-pos">
                <a href="{{ book.get_absolute_url }}">Quick View</a>
            </div>
            
        </div>
        <h4>
            <a href="{{ book.get_absolute_url }}">{{ book.title|truncatechars:20 }}</a>
        </h4>
        
        <div class="simpleCart_shelfItem products-right-grid1-add-cart">
            <p>
                <!-- <i>$325</i> -->
                
                <span class="item_price">{% if book.price == 0.00 %}Free{% else %}₦{{ book.price|intcomma }}{% endif %}</span>
                {% include "./add_to_cart_btn.html" with book=book cart_product_form=cart_product_form %}
                <!-- <a class="item_add" href="#">{% if book.price == 0.00 %}download{% else %}add to cart{% endif %} </a> -->
            </p>
        </div>
    </div> 

shop/templates/shop/partials/new_listing.html
{% load humanize %}
{% load daguerre %}
<div class="new-collections-grid1 animated wow slideInUp" data-wow-delay=".5s">
        <div class="new-collections-grid1-image">
            <a href="{{ book.get_absolute_url }}" class="product-image">
                {% if book.image %}
                <img src="{% adjust book.image 'fill' width=180 height=236 %}" 
                  class="img-responsive" alt="{{ book.title }}">
                {% else %}
                <img src="{{ book.image_url }}" class="img-responsive" height="236" width="180" alt="{{ book.title }}">
                {% endif %}
            </a>
            <div class="new-collections-grid1-image-pos">
                <a href="{{ book.get_absolute_url }}">Quick View</a>
            </div>
            
        </div>
        <h4><a href="{{ book.get_absolute_url }}">{{ book.title|truncatechars:20 }}</a></h4>
        
        <div class="new-collections-grid1-left simpleCart_shelfItem">
            <p>
                <!-- <i>$325</i>  -->
                <span class="item_price">{% if book.price == 0.00 %}Free{% else %}₦{{ book.price|intcomma }}{% endif %}</span>
                {% include "shop/partials/add_to_cart_btn.html" with book=book cart_product_form=cart_product_form %}</p>
        </div>
    </div>

shop/templates/shop/partials/pagination.html
    <nav class="numbering animated wow slideInRight" data-wow-delay=".5s">
            <ul class="pagination paging">
                    {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% else %}
                <li class="disabled">
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% if page_obj.number|add:'-4' > 1 %}
            <li><a href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="active">
                    <a href="#">{{ i }}
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
            {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
            
            <li>
                    <a href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
            {% endfor %}
            {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
            <li><a href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
            {% endif %}
            {% if page_obj.has_next %}
        
        <li>
                <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
        <li class="disabled">
                <a href="" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
    {% endif %}
                
            </ul>
        </nav>

shop/templates/shop/partials/related_books.html
{% load humanize %}
{% load daguerre %}
<div class="single-related-products">
    <div class="container">
        <h3 class="animated wow slideInUp" data-wow-delay=".5s">Related Books</h3>
        <!-- <p class="est animated wow slideInUp" data-wow-delay=".5s">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia 
            deserunt mollit anim id est laborum.</p> -->
        <div class="new-collections-grids">
            {% for book in similar_books %}


            <div class="col-md-3 new-collections-grid">
                <div class="new-collections-grid1 animated wow slideInLeft" data-wow-delay=".5s">
                    <div class="new-collections-grid1-image">
                        <a href="{{ book.get_absolute_url }}" class="product-image">
                            {% if book.image %}
                            <img src="{% adjust book.image 'fill' width=180 height=236 %}" alt="{{ book.title }}" class="img-responsive">
                            {% else %}
                            <img src="{{ book.image_url }}" alt="{{ book.title }}" class="img-responsive" height="236" width="180">
                            {% endif %}
                        </a>
                        <div class="new-collections-grid1-image-pos">
                            <a href="{{ book.get_absolute_url }}">Quick View</a>
                        </div>
                        
                    </div>
                    <h4>
                        <a href="{{ book.get_absolute_url }}">{{ book.title|truncatechars:25 }}</a>
                    </h4>

                    <div class="new-collections-grid1-left simpleCart_shelfItem">
                        <p>
                            <i></i>
                            <span class="item_price">{% if book.price == 0.00 %}Free{% else %}₦{{ book.price|intcomma }}{% endif %}</span>
                            {% include "./add_to_cart_btn.html" with book=book cart_product_form=cart_product_form %}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="clearfix"> </div>
        </div>
    </div>
</div>