cart/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<book_id>\d+)/$',
        views.cart_add,
        name='cart_add'),
    url(r'^remove/(?P<book_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]

myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from shop.views import home, search, profile_edit, profile_view
from django.contrib.sitemaps.views import sitemap
from shop.sitemaps import BookSitemap

admin.site.site_header = 'DLearn admin'
admin.site.site_title = 'DLearn admin'
# admin.site.site_url = 'http://dLearn.tk/'
admin.site.index_title = 'DLearn Administration'

sitemaps = {
    'books': BookSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include("shop.urls", namespace="shop")),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^ratings/', include('star_ratings.urls',
                              namespace='ratings', app_name='ratings')),
    url(r'^daguerre/', include('daguerre.urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^account/profile/$', profile_view, name="profile_view"),
    url(r'^account/profile/edit/$', profile_edit, name="profile_edit"),
    url(r'^search/$', search, name="search"),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt', include('robots.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^$', home, name="home"),
]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^list/orders/$', views.order_list, name='order_list'),
    url(r'^(?P<order_id>\d+)/download/$', views.confirm_payment, name='download'),
    url(r'^(?P<order_id>\d+)/(?P<tx_ref>[\d\w]+)/$', views.order_detail, name='order_detail'),
    url(r'^form/$', views.guest_checkout, name='order_form'),
]

orders/models.py
from django.db import models
from shop.models import Book
from .utils import transaction_reference_generator
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    # Transaction Reference
    tx_ref = models.CharField(
        max_length=30, blank=True, null=True, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def save(self, *args, **kwargs):
        if not self.tx_ref:
            self.tx_ref = transaction_reference_generator()
        super(Order, self).save(*args, **kwargs)  # Call the real save() method


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items')
    book = models.ForeignKey(Book,
                             related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[
                                MinValueValidator(0, "Prices can't be negative")])
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

    def clean(self):
        if self.price < 0:
            raise ValidationError("Prices can't be negative")
        if self.quantity < 0:
            raise ValidationError("Quantity can't be negative")

    def save(self, *args, **kwargs):
        self.clean()
        # Call the real save() method
        super(OrderItem, self).save(*args, **kwargs)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email']

orders/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, get_list_or_404, render

from cart.cart import Cart
from paystackapi.paystack import Paystack
from django.urls import reverse_lazy
from django.core.mail import send_mail
from .forms import OrderCreateForm
from .models import Order, OrderItem
from .tasks import order_created
from .utils import create_order_items

def order_created_mail(order_id, tx_ref):
    """
    Task to send an e-mail notification when an order is
    successfully created.
    """
    order = Order.objects.get(id=order_id, tx_ref=tx_ref)
    download_url = "http://dlearn.tk{}".format(reverse_lazy(
        "orders:order_detail", kwargs={'order_id': order_id, 'tx_ref': tx_ref}))
    subject = 'Order nr. {}'.format(order.id)
    message = 'Dear {},\n\nYou have successfully placed an order.\
    Your order id is {}.\n\nClick on the link below to download \
    your resource. \n\n {}'.format(order.first_name, order.id, download_url)
    mail_sent = send_mail(subject, message, 'snpet.hub@gmail.com', [order.email])

    return mail_sent


def order_create(request):
    ctx = {}
    cart = Cart(request)
    payment_public_key = settings.PAYSTACK_PUBLIC_KEY
    ctx['payment_public_key'] = payment_public_key
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            create_order_items(cart, order, OrderItem)

            ctx['order'] = order
            ctx['cart'] = cart
            order_created_mail(order.id, order.tx_ref)
            order_created.delay(order.id, order.tx_ref)

            return render(request, 'orders/order/created.html', ctx)
    else:

        if request.user.is_authenticated:
            first_name = request.user.first_name or request.user.username
            last_name = request.user.last_name or request.user.username

            email = request.user.email
            order = Order.objects.create(first_name=first_name,
                                         last_name=last_name,
                                         email=email)
            create_order_items(cart, order, OrderItem)
            ctx['order'] = order
            return render(request, 'orders/order/created.html', ctx)

        else:
            return render(request, 'orders/order/checkout_options.html')


def guest_checkout(request):
    # display an order form
    form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'form': form})


def confirm_payment(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    cart = Cart(request)
    paystack = Paystack(secret_key=settings.PAYSTACK_SECRET_KEY)
    response = paystack.transaction.verify(reference=order.tx_ref)

    if response['data']['status'] == "success":
        if response['data']['amount'] == (cart.get_total_price() * 100):
            order.paid = True
            order.save()
            # clear the cart
            cart.clear()
            # launch asynchronous task
            order_created_mail(order.id, order.tx_ref)
            order_created.delay(order.id, order.tx_ref)
            return render(request, 'orders/order/done.html',
                          {'order': order})
    else:
        status = response['data']['status']
        gateway_response = response['data']['gateway_response']
        return render(request, "orders/order/failed.html",
                      {'status': status, "response": gateway_response})


@login_required
def order_list(request):
    # get all orders by a customer
    object_list = Order.objects.filter(email=request.user.email)
    user = request.user
    profile_upto_date = all([user.email, user.first_name,
                             user.last_name, user.username])
    paginator = Paginator(object_list, 20)
    page = request.GET.get('page')
    try:

        orders = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        orders = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        orders = paginator.page(paginator.num_pages)
    return render(request, 'orders/order/order_list.html',
                  {'orders': orders,
                   'profile_update': profile_upto_date})


def order_detail(request, order_id, tx_ref):
    order = get_object_or_404(Order, id=order_id, tx_ref=tx_ref)
    profile_upto_date = None
    if request.user.is_authenticated:
        user = request.user
        profile_upto_date = all([user.email, user.first_name,
                             user.last_name, user.username])
    return render(request, "orders/order/order_detail.html", {'order': order, 'profile_update': profile_upto_date})

orders/templates/orders/order/checkout_options.html
{% extends "shop/base.html" %}

{% block title %}
    Checkout Options
{% endblock title %}


{% block content %}
    
<!-- breadcrumbs -->

<div class="breadcrumbs">
        <div class="container">
            <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
                <li><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
                <li class="active">Checkout Options</li>
            </ol>
        </div>
    </div>
    <!-- //breadcrumbs -->
<div class="container">
    <div class="typo-grids">
<div class="grid_3 grid_5 animated wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
    <h3>Checkout Options</h3>
    <div class="well">
        <h4><a href="{% url 'account_login' %}">Login</a>  or <a href="{% url 'account_signup' %}">Sign-up</a> to checkout (recommended)</h4>
        <p style="font-size: 1.2em">
            You won't have to fill out an order form anytime you want to
            checkout. Also, Your orders are saved for future reference.
        </p>
    </div>
    <div class="well">
       <h4><a href="{% url 'orders:order_form' %}">Checkout as Guest</a></h4>
       <p style="font-size: 1.2em">No login or signup required. Just fill out the order form to get your items.</p>
    </div>
    
</div>
</div>
</div>
{% endblock content %}

orders/templates/orders/order/create.html
{% extends "shop/base.html" %} {% include 'shop/partials/breadcrumbs.html' %} {% block content %}
<div class="register">
    <div class="container">
        <h3 class="animated wow zoomIn" data-wow-delay=".5s">Checkout</h3>
        <p class="est animated wow zoomIn" data-wow-delay=".5s"><b>Fill out this form to checkout</b></p>
        <div class="login-form-grids">
            <form class="animated wow slideInUp" data-wow-delay=".5s" action="{% url 'orders:order_create' %}" method="post">
                {% csrf_token %}
                <input type="text" placeholder="First Name..." required=" " name="{{ form.first_name.name }}">
                <input type="text" placeholder="Last Name..." required=" " name="{{ form.last_name.name }}">
                <input type="email" placeholder="Email Address" required=" " name="{{ form.email.name }}">
                <input type="submit" value="Place Order">
            </form>

        </div>
        <div class="register-home animated wow slideInUp" data-wow-delay=".5s">
            <a href="{% url 'home' %}">Home</a>
        </div>
    </div>
</div>
{% endblock content %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %} 
{% load static %}
{% block title %} Payments {% endblock %} {% block content %}
<!-- {% load ravepay %} -->

<!-- breadcrumbs -->

<div class="breadcrumbs">
        <div class="container">
            <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
                <li><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
                <li><a href="{% url 'cart:cart_detail' %}"><span class="" aria-hidden="true"><img src="{% static 'shop/images/bag.png' %}"></span>Cart</a></li>
                <li class="active">Payments</li>
            </ol>
        </div>
    </div>
    <!-- //breadcrumbs -->
<div class="register">
    <div class="container">
        <h3 class="animated wow zoomIn" data-wow-delay=".5s">Checkout</h3>
        
        <p class="est animated wow zoomIn animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: zoomIn;">
            Click the button below to make payments</p>
        <div class="login-form-grids">
            <p>You're almost done. Just <b>click</b> the button below to <b>pay</b> for your order.</p>
            <form action="{% url 'orders:download' order.id %}" method="POST">
                {% csrf_token %}
                <script src="https://js.paystack.co/v1/inline.js" 
                    data-key="{{ payment_public_key }}" 
                    data-email={{ order.email }} 
                    data-amount={% widthratio cart.get_total_price 1 100 %} 
                    data-ref={{ order.tx_ref }}
                    >
                    </script>
            </form>
            
        </div>

        <div class="register-home animated wow slideInUp" data-wow-delay=".5s">
            <a href="{% url 'home' %}">Home</a>
        </div>

    </div>

</div>
{% endblock content %}

orders/templates/orders/order/done.html
{% extends "shop/base.html" %} {% block title %} Payments {% endblock %} {% block content %}

<div class="register">
    <div class="container">
        <h3 class="animated wow zoomIn" data-wow-delay=".5s">Checkout</h3>
        
        <p class="est animated wow zoomIn animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: zoomIn;">
            Click the button below to make payments</p>
        <div class="login-form-grids">
            <p>Thank you for your purchase. Click on the links below to download the various materials. <b>We've also sent a link to your email address click it to download at a future date</b></p>
            <ul>
                
                <div class="categories animated wow slideInUp" data-wow-delay=".5s">
                    
                  
                    <ul class="cate">
                        {% for item in order.items.all %}
                      <li>
                            <a href="{% if item.book.book_file %}{{ item.book.book_file.url }}{% else %}{{ item.book.book_url }}{% endif %}" download="{% if item.book.book_file %}{{ item.book.book_file.url }}{% else %}{{ item.book.book_url }}{% endif %}">{{ item.book.name }}</a>
                      </li>
                        
                        {% endfor %}
                        
                        
                    </ul>
                </div>
                
                </ul>
            
        </div>

        <div class="register-home animated wow slideInUp" data-wow-delay=".5s">
            <a href="{% url 'home' %}">Home</a>
        </div>

    </div>

</div>
{% endblock content %}

orders/templates/orders/order/failed.html
<p>
    <h3>An Error Occurred. Payments could not be completed</h3>
    <ul>
        <li>Status: {{ status }}</li>
        <li>Server Response: {{ response }}</li>
    </ul>
    Go back to the <a href="{% url 'cart:cart_detail'  %}">cart</a>
</p>  

orders/templates/orders/order/order_detail.html
{% extends "shop/base.html" %}
{% load humanize %}
{% block title %}
    Order Detail
{% endblock title %}
    
{% block content %}
<!-- breadcrumbs -->

<div class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
            <li><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
            
            <li><a href="{% url 'orders:order_list' %}"><span class="glyphicon glyphicon-list" aria-hidden="true"></span>Order list</a></li>
            <li class="active">Order Detail</li>
        </ol>
    </div>
</div>
<!-- //breadcrumbs -->
<!--typography-page -->

<div class="typo">
    <div class="container">
            {% with total_items=order.items.all|length %}
            
            <div class="alert alert-success text-center">
                There {% if total_items == 1 %}is{% else %}are{% endif %} {{ total_items }} item{{ total_items|pluralize }} in this order.
            </div>
            {% endwith %}
            
            {% if request.user.is_authenticated %}
                
            
                
             {% if not profile_update %}
            <div class="alert alert-danger text-center">
                Your profile needs to be updated. Click
                <a href="{% url 'profile_edit' %}">here</a> to update it.
            </div>
            
            {% endif %}
            {% endif %}
        <div class="typo-grids">
        
        <div class="grid_3 grid_4 animated wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
            <div class="col-md-6">
            <h3 class="hdg">Books in order</h3>
            <div class="bs-example">
                <table class="table">
                    <tbody>
                        
                        {% if not order %}
                            <p>No orders available.</p>
                        {% endif %}
                            
                        {% for item in order.items.all %}
                          
                        
                        <tr>
                            <td><h4 id="h4.-bootstrap-heading">{{ item.book.name }}<a class="anchorjs-link" href="#h1.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h1></td>
                            {% if order.paid %}<td class="type-info"><a href="{% if item.book.book_file %}{{ item.book.book_file.url }}{% else %}{{ item.book.book_url }}{% endif %}" download="{{ order.book.book_file.url }}"><span class="label label-success">Download</span></a></td>{% endif %}
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
        </div>
                    
                    
        <div class="col-md-6">
            <h3>Order Details</h3>
            <div class="list-group list-group-alternate"> 
                <a href="#" class="list-group-item"><span class="badge">₦{{ order.get_total_cost|intcomma }}</span> <i class="ti ti-email"></i> Total cost </a> 
                <a href="#" class="list-group-item"><span class="badge badge-primary">{{ order.id }}</span> <i class="ti ti-eye"></i> Order ID </a> 
                <a href="#" class="list-group-item"><span class="badge">{{ order.tx_ref }}</span> <i class="ti ti-headphone-alt"></i> Transaction Ref. </a> 
                <a href="#" class="list-group-item"><span class="badge">{{ order.first_name }}</span> <i class="ti ti-comments"></i> First Name </a> 
                <a href="#" class="list-group-item"><span class="badge badge-warning">{{ order.last_name }}</span> <i class="ti ti-bookmark"></i> Last Name </a> 
                <a href="#" class="list-group-item"><span class="badge badge-{% if order.paid %}success{% else %}danger{% endif %}">{{ order.paid }}</span> <i class="ti ti-bell"></i> Paid </a> 
            </div>
        </div>
        <div class="clearfix"> </div>
               	
        </div>
        
        </div>
    </div>
</div>
<!-- //typography-page -->
{% endblock content %}

orders/templates/orders/order/order_list.html
{% extends "shop/base.html" %}


{% block title %}
    Orders
{% endblock title %}
    
{% block content %}
    
<!-- breadcrumbs -->

<div class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
            <li><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
            <li class="active"><span class="glyphicon glyphicon-list" aria-hidden="true"></span>Order list</li>
        </ol>
    </div>
</div>
<!-- //breadcrumbs -->
<div class="container">
     
    <div class="typo-grids">
        <br>
            {% if request.user.is_authenticated %} {% if not profile_update %}
            <div class="alert alert-danger text-center">
                Your profile needs to be updated. Click
                <a href="{% url 'profile_edit' %}">here</a> to update it.
            </div>
            
            {% endif %} {% endif %}
        <div class="grid_3 grid_5 animated wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
            
            {% if orders %}
                 
            <div class="">
                <p>Click on any of the order to view details</p>
                    <a href="#" class="list-group-item">
                            <span class="badge badge-success"><b></b>Created date</b></span>
                            <i class="ti ti-email"></i> <b>Order ref.</b>
                        </a>
                    
                <div class="list-group list-group-alternate">
                    {% for order in orders %}
                    <a href="{% url 'orders:order_detail' order.id order.tx_ref %}" class="list-group-item">
                        <span class="badge">{{ order.created }}</span>
                        <i class="ti ti-email"></i> {{ order.tx_ref }}
                    </a>
                    {% endfor %}
                    
                    
                </div>
            </div>
            {% else %}
            <p class="text-center"><b>You don't have any orders yet. Purchase an Item and come back to this page.</b></p>
            {% endif %}
            {% include "shop/partials/pagination.html" with page_obj=orders %}
            <div class="clearfix"> </div>
        </div>
        
    </div>
</div>
{% endblock content %}